<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
    <PackageReference Include="SonarAnalyzer.CSharp" Version="10.34.0.3385">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Domain/Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Bootstrap\" />
    <Folder Include="Mappers\" />
    <Folder Include="Enum\" />
    <Folder Include="UseCases\Subasta\Query\Listar\" />
    <Folder Include="UseCases\Usuario\Command\" />
    <Folder Include="UseCases\Usuario\Query\" />
  </ItemGroup>

</Project>
